#!/bin/bash
# Script for installing the EC Web

echo "Welcome to the EC Web installation script!"

# Detect what type of Linux distribution is used to determine LAMP installation script.
echo "Checking if LAMP stack is installed..."
(cat /proc/version | grep ubuntu &> /dev/null && ./scripts/install-ubuntu.sh) || (cat /proc/version | grep red-hat && echo "Uses Red Hat!")

echo "LAMP stack has been installed..."


# Creates the database and populate it with data.
echo "Installing mothy database..."
./scripts/database-mothy-update.sh

# Creates the data file path in the MySQL data file directory
sudo mkdir /var/lib/mysql-files/ec-web
sudo mkdir /var/lib/mysql-files/ec-web/data-mothy
