#!/bin/bash
# Script for installing the EC Web

echo "Welcome to the EC Web installation script!"

# Detect what type of Linux distribution is used to determine LAMP installation script.
echo "Checking if LAMP stack is installed..."
(cat /proc/version | grep ubuntu &> /dev/null && ./scripts/install-ubuntu.sh) || (cat /proc/version | grep red-hat && echo "Uses Red Hat!")

echo "LAMP stack has been installed..."

# Creates a symbolic link to the website
cd /var/www/html
sudo ln -s /home/$USER/evillious_web ec_web
cd /home/$USER/evillious_web

# Creates the database and populate it with data.
echo "Installing mothy database..."
./scripts/database-mothy-update.sh
